language: node_js
node_js: 13.12.0
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_extended_0.70.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    - npm install

branches:
    only:
        - site-source

script:
    - npm run build
    - dir

after_success:
    - git config --global user.name "FFRaycoder"
    - git config --global user.email "nn_201312@163.com"
    - git clone https://${GH_TOKEN}@github.com/FFRaycoder/blog-built.git container
    - git clone https://${GH_TOKEN}@github.com/FFRaycoder/ffraycoder.github.io.git container2
    - rm -rf container/*
    - rm -rf container2/*
    - cp -r public/* container
    - cp -r public/* container2
    - cd container
    - mv Robots.txt robots.txt
    - git add -A
    - git commit -m 'Travis update blog'
    - git push -u origin master -f
    - cd container2
    - mv Robots.txt robots.txt
    - git add -A
    - git commit -m 'Travis update blog'
    - git push -u origin master -f