language: node_js
node_js: 13.12.0
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.71.0/hugo_extended_0.71.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    - npm install

branches:
    only:
        - site-source

script:
    - hugo --gc --minify --cleanDestinationDir

after_success:
    - git config --global user.name "FFRaycoder"
    - git config --global user.email "nn_201312@163.com"
    - cd public
    - git init
    - git remote add origin https://${GH_TOKEN}@github.com/ThemeTony/hugo-theme-tony.git
    - git add -A
    - git commit -m 'Travis update demo site'
    - git branch gh-pages
    - git checkout gh-pages
    - git push -u origin gh-pages -f