language: node_js
node_js: 13.12.0
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_extended_0.70.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    - npm install

branches:
    only:
        - site-source

script:
    - hugo --gc --minify --cleanDestinationDir

after_success:
    - git config --global user.name "FFRaycoder"
    - git config --global user.email "nn_201312@163.com"
    - git clone https://${GH_TOKEN}@github.com/ThemeTony/hugo-theme-tony.git container
    - rm -rf container/*
    - cp -r public/* container
    - cd container
    - git add -A
    - git commit -m 'Travis update demo site'
    - git push -u origin gh-pages -f