########################################
# Site configuration
# Icon: https://RemixIcon.com/

baseURL = "http://example.com/"
title = "HUGO-THEME-TONY"
languageCode = "en"
hasCJKLanguage = false

# Theme selection
theme = "tony"

# `hugo new` text editor for automatically opening new articles
newContentEditor = ""

# Summary word limit
summaryLength = 235

# Whether to enable GitHub style Emoji writing
enableEmoji = true

# Number of articles per page
paginate = 10

# author information
[author]
    # Name
    name = ""
    # Mailbox
    email = ""
    # Motto or introduction
    motto = ""
    # Avatar
    avatar = "/images/t.jpg"
    # Website (default: baseURL)
    website = "https://themetony.github.io/hugo-theme-tony/"
    # GitHub
    github = ""

# Page category
[taxonomies]
  category = "categories"
  tag = "tags"

########################################
# Menu configuration

# The configuration instructions in the menu are as follows:
# url link address
# name text (leave blank ("") no)
# weight

[menu]
    # Menu Bar
    [[menu.main]]
        url = "/"
        name = "Home"
        weight = 1
    [[menu.main]]
        url = "/about/"
        name = "About"
        weight = 2

[[params.pinned]]
    title = "HUGO-THEME-TONY"
    name = "HUGO-THEME-TONY"
    icon = "ri-code-box-line"
    url = "https://htony.js.org/"

# Markdown renderer
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = false
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = true

# Hugo output control
[outputs]
    page = ["HTML"]
    home = ["HTML"]
    section = ["HTML"]
    # Category
    taxonomyTerm = ["HTML"]
    # Category item
    taxonomy = ["HTML"]
    # Description: https://github.com/gohugoio/hugo/issues/4528#issuecomment-508488859

########################################
# Theme configuration

[params]

    #####################################
    # Site Information

    # Site LOGO
    siteLogo = "/images/t.jpg"

    # Site creation time
    siteCreatedTime = "2019"
    # Note: Please keep this format and change the number

    #####################################
    # table of Contents
    
    # Whether to open (global settings)
    enableToc = true

    #####################################
    # Reading progress bar
    
    # Whether to open (global settings)
    enableReadingBar = true

    #####################################
    # Article up and down page
    
    # Whether to open (global settings)
    enableAdjacentPost = true

    #####################################
    # Whether to show the link between Hugo and Tony

    displayPoweredBy = true

    #####################################
    # Markdown Related

    # Open link in new tab page?
    hrefTargetBlank = true

    #####################################
    # Comments

    # Whether to open (global settings)
    enableComments = false
    # Description: "comments" in the front Matter of the article
    # Has priority over here

    ## Valine
    enableValine = false
    valineVersion = "latest"
    valineAppId = ""
    valineAppKey = ""
    valinePlaceholder = ""
    valinePath = ""
    valineAvatar = "mm"
    valineMeta = ["nick", "mail", "link"]
    valinePageSize = 15
    valineVisitor = true
    valineHighlight = true
    avatarForce = true
    valineRecordIP = true
    valineServerURLs = ""
    valineEnableQQ = false
    valineRequiredFields = []
    # Description: https://valine.js.org/

    #####################################
    # Google Analytics

    enableGoogleAnalytics = false

    # Type of tracking code
    trackingCodeType = ""
    # Description: gtag or analytics

    trackingID = ""

    #####################################
    # Google Site Verification

    googleSiteVerification = ""


    #####################################
    # Baidu push

    enableBaiduPush = true